title: Nexum
description: Протокол эволюции человека
url: "https://www.nexum.space"
baseurl: ""
lang: ru

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap

exclude:
  - info.txt
  - README.md
  - "*.sh"
